name:          DTS 前端开发规范
description:   Standards for developing flexible, durable, and sustainable HTML and CSS, and maintainable JavaScript
url:           https://lee84233.github.io/html-standard/

markdown:      rdiscount
permalink:     pretty
pygments:      true
